import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */`;
const production = process.argv[2] === "production";
const builtins = builtinModules.map((name) => name.replace(/^node:/, ""));

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  platform: "node",
  external: [
    "obsidian",
    "electron",
    "cpu-features",
    ...builtins,
    ...builtins.map((name) => `node:${name}`)
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js"
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
