/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TomosPublisherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  tomosUrl: "",
  token: "",
  articleFolder: ""
};
var TOMOS_MARKDOWN_GUIDE_URL = "https://tomoswords.org/docs/markdown/";
var MAX_IMAGE_COUNT = 5;
var MAX_IMAGE_BYTES = 10 * 1024 * 1024;
var IMAGE_CHUNK_BYTES = 512 * 1024;
var IMAGE_EXTENSIONS = {
  jpg: { extension: "jpg", mimeType: "image/jpeg" },
  jpeg: { extension: "jpg", mimeType: "image/jpeg" },
  png: { extension: "png", mimeType: "image/png" },
  gif: { extension: "gif", mimeType: "image/gif" },
  webp: { extension: "webp", mimeType: "image/webp" }
};
var TOMOS_ARTICLE_TEMPLATE = `---
title: \u8A18\u4E8B\u306E\u30BF\u30A4\u30C8\u30EB
# \u516C\u958B\u5148\u30D5\u30A9\u30EB\u30C0\u30FC\u3092\u6307\u5B9A\u3057\u307E\u3059\u3002\u4F8B: diary / blog
folder: diary
# \u6295\u7A3F\u65E5\u3092\u6307\u5B9A\u3059\u308B\u5834\u5408\u306FYYYY-MM-DD\u5F62\u5F0F\u3002\u7A7A\u6B04\u306A\u3089\u521D\u56DE\u516C\u958B\u65E5\u306B\u81EA\u52D5\u88DC\u5B8C\u3055\u308C\u307E\u3059
date:
draft: false
tags:
  - \u65E5\u8A18
  - Tomos
---

# \u8A18\u4E8B\u306E\u30BF\u30A4\u30C8\u30EB

\u3053\u3053\u306B\u672C\u6587\u3092\u66F8\u304D\u307E\u3059\u3002

## \u898B\u51FA\u3057

\u6BB5\u843D\u3092\u66F8\u304D\u307E\u3059\u3002

- \u7B87\u6761\u66F8\u304D
- \u7B87\u6761\u66F8\u304D

[\u30EA\u30F3\u30AF\u306E\u6587\u5B57](https://example.com/)

Obsidian\u306B\u4FDD\u5B58\u3057\u305F\u753B\u50CF\u306F\u3001\u901A\u5E38\u306E\u753B\u50CF\u8A18\u6CD5\u307E\u305F\u306F ![[image.jpg]] \u3067\u8CBC\u308A\u4ED8\u3051\u3066Tomos\u3078\u9001\u4FE1\u3067\u304D\u307E\u3059\u3002

[[\u5225\u306E\u8A18\u4E8B]]
`;
var TomosPublisherPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "create-tomos-article",
      name: "Tomos\u8A18\u4E8B\u3092\u65B0\u898F\u4F5C\u6210",
      callback: async () => {
        await this.createTomosArticle();
      }
    });
    this.addCommand({
      id: "open-tomos-markdown-guide",
      name: "Tomos\u7528Markdown\u306E\u66F8\u304D\u65B9\u3092\u958B\u304F",
      callback: () => {
        this.openMarkdownGuide();
      }
    });
    this.addCommand({
      id: "upload-current-markdown-to-tomos",
      name: "Tomos\u3078\u9001\u4FE1",
      callback: async () => {
        await this.sendCurrentFileToTomos();
      }
    });
    this.addRibbonIcon("send", "Tomos\u3078\u9001\u4FE1", async () => {
      await this.sendCurrentFileToTomos();
    });
    this.addSettingTab(new TomosPublisherSettingTab(this.app, this));
  }
  async createTomosArticle() {
    const path = this.findAvailableArticlePath(this.articleFolderPath());
    try {
      const file = await this.app.vault.create(path, TOMOS_ARTICLE_TEMPLATE);
      await this.app.workspace.getLeaf(false).openFile(file);
      new import_obsidian.Notice("Tomos\u8A18\u4E8B\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F\u3002");
    } catch {
      new import_obsidian.Notice("Tomos: \u8A18\u4E8B\u3092\u4F5C\u6210\u3067\u304D\u307E\u305B\u3093\u3067\u3057\u305F\u3002");
    }
  }
  articleFolderPath() {
    let configured = this.settings.articleFolder.trim().replace(/^\/+|\/+$/g, "");
    if (configured === "") return "";
    configured = (0, import_obsidian.normalizePath)(configured);
    const target = this.app.vault.getAbstractFileByPath(configured);
    return target && "children" in target ? configured : "";
  }
  findAvailableArticlePath(folderPath) {
    const baseName = "Tomos\u8A18\u4E8B";
    let suffix = 0;
    while (true) {
      const fileName = suffix === 0 ? `${baseName}.md` : `${baseName} ${suffix}.md`;
      const candidate = (0, import_obsidian.normalizePath)(folderPath ? `${folderPath}/${fileName}` : fileName);
      if (!this.app.vault.getAbstractFileByPath(candidate)) return candidate;
      suffix += 1;
    }
  }
  openMarkdownGuide() {
    window.open(TOMOS_MARKDOWN_GUIDE_URL, "_blank");
  }
  validateSettings() {
    const tomosUrl = this.settings.tomosUrl.trim();
    if (!/^https:\/\/[^\s]+$/i.test(tomosUrl)) return "Tomos URL\u306Fhttps://\u3067\u59CB\u307E\u308BURL\u3092\u8A2D\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002";
    if (this.settings.token.trim() === "") return "\u6295\u7A3F\u7528\u30C8\u30FC\u30AF\u30F3\u304C\u672A\u8A2D\u5B9A\u3067\u3059\u3002";
    try {
      const url = new URL(tomosUrl);
      if (url.username || url.password || url.hash) return "Tomos URL\u304C\u6B63\u3057\u304F\u3042\u308A\u307E\u305B\u3093\u3002";
    } catch {
      return "Tomos URL\u304C\u6B63\u3057\u304F\u3042\u308A\u307E\u305B\u3093\u3002";
    }
    return null;
  }
  async testConnection() {
    const invalid = this.validateSettings();
    if (invalid) {
      new import_obsidian.Notice(`Tomos: ${invalid}`);
      return;
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: this.apiUrl(),
        method: "GET",
        headers: { "X-Tomos-Token": this.settings.token.trim() },
        throw: false
      });
      if (response.status === 200) {
        new import_obsidian.Notice("Tomos\u63A5\u7D9A\u30C6\u30B9\u30C8\u306B\u6210\u529F\u3057\u307E\u3057\u305F\u3002");
      } else if (response.status === 401) {
        new import_obsidian.Notice("Tomos: \u8A8D\u8A3C\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
      } else {
        new import_obsidian.Notice("Tomos: \u63A5\u7D9A\u30C6\u30B9\u30C8\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
      }
    } catch {
      new import_obsidian.Notice("Tomos: Tomos URL\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
    }
  }
  async sendCurrentFileToTomos() {
    const invalid = this.validateSettings();
    if (invalid) {
      new import_obsidian.Notice(`Tomos: ${invalid}`);
      return;
    }
    const file = this.app.workspace.getActiveFile();
    if (!(file instanceof import_obsidian.TFile) || file.extension.toLowerCase() !== "md") {
      new import_obsidian.Notice("Tomos: Markdown\u30D5\u30A1\u30A4\u30EB\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044\u3002");
      return;
    }
    let uploadId = "";
    try {
      const content = await this.app.vault.read(file);
      const prepared = await this.preparePost(content, file);
      if (prepared.images.length === 0) {
        const response = await this.postJson({ filename: file.name, content: prepared.content });
        this.showSendResult(response.status, this.responseMessage(response));
        return;
      }
      const start = await this.postJson({
        action: "start",
        filename: file.name,
        content: prepared.content,
        images: prepared.images.map((image) => image.name)
      });
      if (start.status < 200 || start.status >= 300) {
        this.showSendResult(start.status, this.responseMessage(start));
        return;
      }
      uploadId = typeof start.json?.upload_id === "string" ? start.json.upload_id : "";
      if (uploadId === "") {
        throw new Error("\u753B\u50CF\u306E\u9001\u4FE1\u6E96\u5099\u60C5\u5831\u3092\u53D7\u3051\u53D6\u308C\u307E\u305B\u3093\u3067\u3057\u305F\u3002");
      }
      for (const image of prepared.images) {
        const sent = await this.sendImage(uploadId, image);
        if (!sent) return;
      }
      const finalize = await this.postJson({ action: "finalize", upload_id: uploadId });
      if (finalize.status < 200 || finalize.status >= 300) {
        await this.cancelImageUpload(uploadId);
        this.showSendResult(finalize.status, this.responseMessage(finalize));
        return;
      }
      uploadId = "";
      new import_obsidian.Notice(`Tomos\u3078\u753B\u50CF${prepared.images.length}\u70B9\u3068Markdown\u3092\u9001\u4FE1\u3057\u307E\u3057\u305F\u3002`);
    } catch (error) {
      if (uploadId !== "") await this.cancelImageUpload(uploadId);
      const message = error instanceof Error ? error.message : "Markdown\u3092\u9001\u4FE1\u3067\u304D\u307E\u305B\u3093\u3067\u3057\u305F\u3002";
      new import_obsidian.Notice(`Tomos: ${message}`);
    }
  }
  async sendImage(uploadId, image) {
    const chunkCount = Math.ceil(image.data.byteLength / IMAGE_CHUNK_BYTES);
    for (let chunkIndex = 0; chunkIndex < chunkCount; chunkIndex += 1) {
      const start = chunkIndex * IMAGE_CHUNK_BYTES;
      const end = Math.min(start + IMAGE_CHUNK_BYTES, image.data.byteLength);
      const response = await (0, import_obsidian.requestUrl)({
        url: this.apiUrl(),
        method: "POST",
        headers: {
          "Content-Type": "application/octet-stream",
          "X-Tomos-Token": this.settings.token.trim(),
          "X-Tomos-Action": "image",
          "X-Tomos-Upload-Id": uploadId,
          "X-Tomos-Image-Name": image.name,
          "X-Tomos-Image-Type": image.mimeType,
          "X-Tomos-Chunk-Index": String(chunkIndex),
          "X-Tomos-Chunk-Count": String(chunkCount),
          "X-Tomos-Total-Size": String(image.data.byteLength)
        },
        body: image.data.slice(start, end),
        throw: false
      });
      if (response.status < 200 || response.status >= 300) {
        await this.cancelImageUpload(uploadId);
        this.showSendResult(response.status, this.responseMessage(response));
        return false;
      }
    }
    return true;
  }
  async preparePost(content, sourceFile) {
    const replacements = [];
    const images = /* @__PURE__ */ new Map();
    const occupied = [];
    const wikiPattern = /!\[\[([^\]\n|]+)(?:\|([^\]\n]*))?\]\]/g;
    let wikiMatch;
    while ((wikiMatch = wikiPattern.exec(content)) !== null) {
      const target = wikiMatch[1].trim();
      const imageFile = this.resolveLocalImage(target, sourceFile);
      if (!imageFile) continue;
      const preparedImage = await this.prepareImage(imageFile);
      images.set(preparedImage.name, preparedImage);
      const alt = (wikiMatch[2] ?? imageFile.basename).trim() || imageFile.basename;
      replacements.push({
        start: wikiMatch.index,
        end: wikiMatch.index + wikiMatch[0].length,
        text: `![${this.escapeAlt(alt)}](images/${preparedImage.name})`
      });
      occupied.push({ start: wikiMatch.index, end: wikiMatch.index + wikiMatch[0].length });
    }
    const markdownPattern = /!\[([^\]\n]*)\]\(([^)\n]+)\)/g;
    let markdownMatch;
    while ((markdownMatch = markdownPattern.exec(content)) !== null) {
      const start = markdownMatch.index;
      const end = start + markdownMatch[0].length;
      if (occupied.some((range) => start >= range.start && end <= range.end)) continue;
      const rawTarget = markdownMatch[2].trim();
      if (/^(?:https?:|data:|#)/i.test(rawTarget)) continue;
      if (/^images\/tms-[a-f0-9]{16}\.(?:jpg|jpeg|png|gif|webp)$/i.test(rawTarget)) continue;
      const target = this.normalizedMarkdownTarget(rawTarget);
      if (target === "") continue;
      const imageFile = this.resolveLocalImage(target, sourceFile);
      if (!imageFile) {
        throw new Error(`\u753B\u50CF\u300C${target}\u300D\u304CVault\u5185\u306B\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3002`);
      }
      const preparedImage = await this.prepareImage(imageFile);
      images.set(preparedImage.name, preparedImage);
      replacements.push({
        start,
        end,
        text: `![${this.escapeAlt(markdownMatch[1])}](images/${preparedImage.name})`
      });
    }
    if (images.size > MAX_IMAGE_COUNT) {
      throw new Error(`\u753B\u50CF\u306F${MAX_IMAGE_COUNT}\u70B9\u307E\u3067\u9001\u4FE1\u3067\u304D\u307E\u3059\u3002`);
    }
    let rewritten = content;
    replacements.sort((left, right) => right.start - left.start);
    for (const replacement of replacements) {
      rewritten = rewritten.slice(0, replacement.start) + replacement.text + rewritten.slice(replacement.end);
    }
    return { content: rewritten, images: Array.from(images.values()) };
  }
  resolveLocalImage(target, sourceFile) {
    let linkPath = target.trim();
    if (linkPath.startsWith("<") && linkPath.endsWith(">")) {
      linkPath = linkPath.slice(1, -1).trim();
    }
    try {
      linkPath = decodeURIComponent(linkPath);
    } catch {
    }
    linkPath = linkPath.replace(/^\/+/, "");
    const file = this.app.metadataCache.getFirstLinkpathDest(linkPath, sourceFile.path);
    if (!(file instanceof import_obsidian.TFile)) return null;
    return IMAGE_EXTENSIONS[file.extension.toLowerCase()] ? file : null;
  }
  normalizedMarkdownTarget(rawTarget) {
    const angleMatch = rawTarget.match(/^<([^>]+)>/);
    if (angleMatch) return angleMatch[1].trim();
    const titleMatch = rawTarget.match(/^(\S+)(?:\s+["'][^"']*["'])?$/);
    return titleMatch ? titleMatch[1].trim() : rawTarget;
  }
  async prepareImage(file) {
    const format = IMAGE_EXTENSIONS[file.extension.toLowerCase()];
    if (!format) throw new Error(`\u753B\u50CF\u300C${file.name}\u300D\u306E\u5F62\u5F0F\u306B\u306F\u5BFE\u5FDC\u3057\u3066\u3044\u307E\u305B\u3093\u3002`);
    const data = await this.app.vault.readBinary(file);
    if (data.byteLength <= 0) throw new Error(`\u753B\u50CF\u300C${file.name}\u300D\u304C\u7A7A\u3067\u3059\u3002`);
    if (data.byteLength > MAX_IMAGE_BYTES) throw new Error(`\u753B\u50CF\u300C${file.name}\u300D\u306F10MB\u4EE5\u4E0B\u306B\u3057\u3066\u304F\u3060\u3055\u3044\u3002`);
    const digest = await crypto.subtle.digest("SHA-256", data);
    const hash = Array.from(new Uint8Array(digest)).map((value) => value.toString(16).padStart(2, "0")).join("");
    return {
      name: `tms-${hash.slice(0, 16)}.${format.extension}`,
      data,
      mimeType: format.mimeType
    };
  }
  escapeAlt(alt) {
    return alt.replace(/\\/g, "\\\\").replace(/\]/g, "\\]").replace(/\n/g, " ");
  }
  async postJson(payload) {
    return (0, import_obsidian.requestUrl)({
      url: this.apiUrl(),
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Tomos-Token": this.settings.token.trim()
      },
      body: JSON.stringify(payload),
      throw: false
    });
  }
  async cancelImageUpload(uploadId) {
    if (uploadId === "") return;
    try {
      await this.postJson({ action: "cancel", upload_id: uploadId });
    } catch {
    }
  }
  responseMessage(response) {
    if (response.json && typeof response.json === "object" && "message" in response.json) {
      const message = response.json.message;
      if (typeof message === "string" && message.trim() !== "") return message;
    }
    return "";
  }
  showSendResult(status, serverMessage = "") {
    if (status >= 200 && status < 300) {
      new import_obsidian.Notice("Tomos\u3078\u9001\u4FE1\u3057\u307E\u3057\u305F\u3002");
    } else if (serverMessage !== "") {
      new import_obsidian.Notice(`Tomos: ${serverMessage}`);
    } else if (status === 401) {
      new import_obsidian.Notice("Tomos: \u8A8D\u8A3C\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
    } else if (status === 409) {
      new import_obsidian.Notice("Tomos: \u540C\u540D\u30D5\u30A1\u30A4\u30EB\u304C\u53D7\u4FE1\u7BB1\u306B\u3042\u308A\u307E\u3059\u3002");
    } else if (status === 413) {
      new import_obsidian.Notice("Tomos: Markdown\u307E\u305F\u306F\u753B\u50CF\u306E\u30B5\u30A4\u30BA\u304C\u5927\u304D\u3059\u304E\u307E\u3059\u3002");
    } else {
      new import_obsidian.Notice("Tomos: Markdown\u3092\u9001\u4FE1\u3067\u304D\u307E\u305B\u3093\u3067\u3057\u305F\u3002");
    }
  }
  apiUrl() {
    return `${this.settings.tomosUrl.trim().replace(/\/+$/, "")}/post/inbox/api/`;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var TomosPublisherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Tomos Publisher" });
    new import_obsidian.Setting(containerEl).setName("Tomos URL").setDesc("\u4F8B: https://tomoswords.org/dev/").addText(
      (text) => text.setPlaceholder("https://tomoswords.org/dev/").setValue(this.plugin.settings.tomosUrl).onChange(async (value) => {
        this.plugin.settings.tomosUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6295\u7A3F\u7528\u30C8\u30FC\u30AF\u30F3").setDesc("Tomos Post\u306E\u30BB\u30AD\u30E5\u30EA\u30C6\u30A3\u753B\u9762\u3067\u767A\u884C\u3057\u305F\u5C02\u7528\u30C8\u30FC\u30AF\u30F3\u3067\u3059\u3002").addText((text) => {
      text.inputEl.type = "password";
      text.setValue(this.plugin.settings.token).onChange(async (value) => {
        this.plugin.settings.token = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Tomos\u8A18\u4E8B\u306E\u4F5C\u6210\u30D5\u30A9\u30EB\u30C0").setDesc("Vault\u5185\u306E\u65E2\u5B58\u30D5\u30A9\u30EB\u30C0\u3092\u6307\u5B9A\u3057\u307E\u3059\u3002\u7A7A\u6B04\u307E\u305F\u306F\u5B58\u5728\u3057\u306A\u3044\u5834\u5408\u306FVault\u30EB\u30FC\u30C8\u3078\u4FDD\u5B58\u3057\u307E\u3059\u3002\u30D5\u30A9\u30EB\u30C0\u306F\u81EA\u52D5\u4F5C\u6210\u3057\u307E\u305B\u3093\u3002").addText(
      (text) => text.setPlaceholder("\u4F8B: Tomos").setValue(this.plugin.settings.articleFolder).onChange(async (value) => {
        this.plugin.settings.articleFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Tomos\u63A5\u7D9A\u30C6\u30B9\u30C8").addButton(
      (button) => button.setButtonText("\u63A5\u7D9A\u30C6\u30B9\u30C8").onClick(async () => {
        await this.plugin.testConnection();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Tomos\u7528Markdown").setDesc("Front Matter\u3084Tomos\u3067\u4F7F\u3048\u308BMarkdown\u8A18\u6CD5\u3092\u516C\u5F0F\u30AC\u30A4\u30C9\u3067\u78BA\u8A8D\u3067\u304D\u307E\u3059\u3002").addButton(
      (button) => button.setButtonText("\u66F8\u304D\u65B9\u3092\u898B\u308B").onClick(() => {
        this.plugin.openMarkdownGuide();
      })
    );
  }
};
