/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TomosPublisherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  tomosUrl: "",
  token: ""
};
var TomosPublisherPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "upload-current-markdown-to-tomos",
      name: "Tomos\u3078\u9001\u4FE1",
      callback: async () => {
        await this.sendCurrentFileToTomos();
      }
    });
    this.addRibbonIcon("send", "Tomos\u3078\u9001\u4FE1", async () => {
      await this.sendCurrentFileToTomos();
    });
    this.addSettingTab(new TomosPublisherSettingTab(this.app, this));
  }
  validateSettings() {
    const tomosUrl = this.settings.tomosUrl.trim();
    if (!/^https:\/\/[^\s]+$/i.test(tomosUrl)) return "Tomos URL\u306Fhttps://\u3067\u59CB\u307E\u308BURL\u3092\u8A2D\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002";
    if (this.settings.token.trim() === "") return "\u6295\u7A3F\u7528\u30C8\u30FC\u30AF\u30F3\u304C\u672A\u8A2D\u5B9A\u3067\u3059\u3002";
    try {
      const url = new URL(tomosUrl);
      if (url.username || url.password || url.hash) return "Tomos URL\u304C\u6B63\u3057\u304F\u3042\u308A\u307E\u305B\u3093\u3002";
    } catch {
      return "Tomos URL\u304C\u6B63\u3057\u304F\u3042\u308A\u307E\u305B\u3093\u3002";
    }
    return null;
  }
  async testConnection() {
    const invalid = this.validateSettings();
    if (invalid) {
      new import_obsidian.Notice(`Tomos: ${invalid}`);
      return;
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: this.apiUrl(),
        method: "GET",
        headers: { "X-Tomos-Token": this.settings.token.trim() },
        throw: false
      });
      if (response.status === 200) {
        new import_obsidian.Notice("Tomos\u63A5\u7D9A\u30C6\u30B9\u30C8\u306B\u6210\u529F\u3057\u307E\u3057\u305F\u3002");
      } else if (response.status === 401) {
        new import_obsidian.Notice("Tomos: \u8A8D\u8A3C\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
      } else {
        new import_obsidian.Notice("Tomos: \u63A5\u7D9A\u30C6\u30B9\u30C8\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
      }
    } catch {
      new import_obsidian.Notice("Tomos: Tomos URL\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
    }
  }
  async sendCurrentFileToTomos() {
    const invalid = this.validateSettings();
    if (invalid) {
      new import_obsidian.Notice(`Tomos: ${invalid}`);
      return;
    }
    const file = this.app.workspace.getActiveFile();
    if (!(file instanceof import_obsidian.TFile) || file.extension.toLowerCase() !== "md") {
      new import_obsidian.Notice("Tomos: Markdown\u30D5\u30A1\u30A4\u30EB\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044\u3002");
      return;
    }
    try {
      const content = await this.app.vault.read(file);
      const response = await (0, import_obsidian.requestUrl)({
        url: this.apiUrl(),
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Tomos-Token": this.settings.token.trim()
        },
        body: JSON.stringify({ filename: file.name, content }),
        throw: false
      });
      if (response.status >= 200 && response.status < 300) {
        new import_obsidian.Notice("Tomos\u3078\u9001\u4FE1\u3057\u307E\u3057\u305F\u3002");
      } else if (response.status === 401) {
        new import_obsidian.Notice("Tomos: \u8A8D\u8A3C\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002");
      } else if (response.status === 409) {
        new import_obsidian.Notice("Tomos: \u540C\u540D\u30D5\u30A1\u30A4\u30EB\u304C\u53D7\u4FE1\u7BB1\u306B\u3042\u308A\u307E\u3059\u3002");
      } else if (response.status === 413) {
        new import_obsidian.Notice("Tomos: Markdown\u306E\u30B5\u30A4\u30BA\u304C\u5927\u304D\u3059\u304E\u307E\u3059\u3002");
      } else {
        new import_obsidian.Notice("Tomos: Markdown\u3092\u9001\u4FE1\u3067\u304D\u307E\u305B\u3093\u3067\u3057\u305F\u3002");
      }
    } catch {
      new import_obsidian.Notice("Tomos: Markdown\u3092\u9001\u4FE1\u3067\u304D\u307E\u305B\u3093\u3067\u3057\u305F\u3002");
    }
  }
  apiUrl() {
    return `${this.settings.tomosUrl.trim().replace(/\/+$/, "")}/post/inbox/api/`;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var TomosPublisherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Tomos Publisher" });
    new import_obsidian.Setting(containerEl).setName("Tomos URL").setDesc("\u4F8B: https://tomoswords.org/dev/").addText(
      (text) => text.setPlaceholder("https://tomoswords.org/dev/").setValue(this.plugin.settings.tomosUrl).onChange(async (value) => {
        this.plugin.settings.tomosUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6295\u7A3F\u7528\u30C8\u30FC\u30AF\u30F3").setDesc("Tomos Post\u306E\u30BB\u30AD\u30E5\u30EA\u30C6\u30A3\u753B\u9762\u3067\u767A\u884C\u3057\u305F\u5C02\u7528\u30C8\u30FC\u30AF\u30F3\u3067\u3059\u3002").addText((text) => {
      text.inputEl.type = "password";
      text.setValue(this.plugin.settings.token).onChange(async (value) => {
        this.plugin.settings.token = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Tomos\u63A5\u7D9A\u30C6\u30B9\u30C8").addButton(
      (button) => button.setButtonText("\u63A5\u7D9A\u30C6\u30B9\u30C8").onClick(async () => {
        await this.plugin.testConnection();
      })
    );
  }
};
