/* THIS IS A GENERATED/BUNDLED FILE BY TYPESCRIPT FOR PUBLIC SYNC */
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const obsidian_1 = require("obsidian");
const DEFAULT_SETTINGS = {
    tomosUrl: "",
    token: "",
    articleFolder: "",
};
const TOMOS_MARKDOWN_GUIDE_URL = "https://tomoswords.org/docs/markdown/";
const MAX_IMAGE_COUNT = 5;
const MAX_IMAGE_BYTES = 10 * 1024 * 1024;
const IMAGE_CHUNK_BYTES = 512 * 1024;
const IMAGE_EXTENSIONS = {
    jpg: { extension: "jpg", mimeType: "image/jpeg" },
    jpeg: { extension: "jpg", mimeType: "image/jpeg" },
    png: { extension: "png", mimeType: "image/png" },
    gif: { extension: "gif", mimeType: "image/gif" },
    webp: { extension: "webp", mimeType: "image/webp" },
};
const TOMOS_ARTICLE_TEMPLATE = `---
title: 記事のタイトル
# 公開先フォルダーを指定します。例: diary / blog
folder: diary
# 投稿日を指定する場合はYYYY-MM-DD形式。空欄なら初回公開日に自動補完されます
date:
draft: false
tags:
  - 日記
  - Tomos
---

# 記事のタイトル

ここに本文を書きます。

## 見出し

段落を書きます。

- 箇条書き
- 箇条書き

[リンクの文字](https://example.com/)

Obsidianに保存した画像は、通常の画像記法または ![[image.jpg]] で貼り付けてTomosへ送信できます。

[[別の記事]]
`;
class TomosPublisherPlugin extends obsidian_1.Plugin {
    constructor() {
        super(...arguments);
        this.settings = DEFAULT_SETTINGS;
    }
    async onload() {
        await this.loadSettings();
        this.addCommand({
            id: "create-tomos-article",
            name: "Tomos記事を新規作成",
            callback: async () => {
                await this.createTomosArticle();
            }
        });
        this.addCommand({
            id: "open-tomos-markdown-guide",
            name: "Tomos用Markdownの書き方を開く",
            callback: () => {
                this.openMarkdownGuide();
            }
        });
        this.addCommand({
            id: "upload-current-markdown-to-tomos",
            name: "Tomosへ送信",
            callback: async () => {
                await this.sendCurrentFileToTomos();
            }
        });
        this.addRibbonIcon("send", "Tomosへ送信", async () => {
            await this.sendCurrentFileToTomos();
        });
        this.addSettingTab(new TomosPublisherSettingTab(this.app, this));
    }
    async createTomosArticle() {
        const path = this.findAvailableArticlePath(this.articleFolderPath());
        try {
            const file = await this.app.vault.create(path, TOMOS_ARTICLE_TEMPLATE);
            await this.app.workspace.getLeaf(false).openFile(file);
            new obsidian_1.Notice("Tomos記事を作成しました。");
        }
        catch {
            new obsidian_1.Notice("Tomos: 記事を作成できませんでした。");
        }
    }
    articleFolderPath() {
        let configured = this.settings.articleFolder.trim().replace(/^\/+|\/+$/g, "");
        if (configured === "")
            return "";
        configured = (0, obsidian_1.normalizePath)(configured);
        const target = this.app.vault.getAbstractFileByPath(configured);
        return target && "children" in target ? configured : "";
    }
    findAvailableArticlePath(folderPath) {
        const baseName = "Tomos記事";
        let suffix = 0;
        while (true) {
            const fileName = suffix === 0 ? `${baseName}.md` : `${baseName} ${suffix}.md`;
            const candidate = (0, obsidian_1.normalizePath)(folderPath ? `${folderPath}/${fileName}` : fileName);
            if (!this.app.vault.getAbstractFileByPath(candidate))
                return candidate;
            suffix += 1;
        }
    }
    openMarkdownGuide() {
        window.open(TOMOS_MARKDOWN_GUIDE_URL, "_blank");
    }
    validateSettings() {
        const tomosUrl = this.settings.tomosUrl.trim();
        if (!/^https:\/\/[^\s]+$/i.test(tomosUrl))
            return "Tomos URLはhttps://で始まるURLを設定してください。";
        if (this.settings.token.trim() === "")
            return "投稿用トークンが未設定です。";
        try {
            const url = new URL(tomosUrl);
            if (url.username || url.password || url.hash)
                return "Tomos URLが正しくありません。";
        }
        catch {
            return "Tomos URLが正しくありません。";
        }
        return null;
    }
    async testConnection() {
        const invalid = this.validateSettings();
        if (invalid) {
            new obsidian_1.Notice(`Tomos: ${invalid}`);
            return;
        }
        try {
            const response = await (0, obsidian_1.requestUrl)({
                url: this.apiUrl(),
                method: "GET",
                headers: { "X-Tomos-Token": this.settings.token.trim() },
                throw: false,
            });
            if (response.status === 200) {
                new obsidian_1.Notice("Tomos接続テストに成功しました。");
            }
            else if (response.status === 401) {
                new obsidian_1.Notice("Tomos: 認証に失敗しました。");
            }
            else {
                new obsidian_1.Notice("Tomos: 接続テストに失敗しました。");
            }
        }
        catch {
            new obsidian_1.Notice("Tomos: Tomos URLを確認してください。");
        }
    }
    async sendCurrentFileToTomos() {
        const invalid = this.validateSettings();
        if (invalid) {
            new obsidian_1.Notice(`Tomos: ${invalid}`);
            return;
        }
        const file = this.app.workspace.getActiveFile();
        if (!(file instanceof obsidian_1.TFile) || file.extension.toLowerCase() !== "md") {
            new obsidian_1.Notice("Tomos: Markdownファイルを開いてください。");
            return;
        }
        let uploadId = "";
        try {
            const content = await this.app.vault.read(file);
            const prepared = await this.preparePost(content, file);
            if (prepared.images.length === 0) {
                const response = await this.postJson({ filename: file.name, content: prepared.content });
                this.showSendResult(response.status, this.responseMessage(response));
                return;
            }
            const start = await this.postJson({
                action: "start",
                filename: file.name,
                content: prepared.content,
                images: prepared.images.map((image) => image.name),
            });
            if (start.status < 200 || start.status >= 300) {
                this.showSendResult(start.status, this.responseMessage(start));
                return;
            }
            uploadId = typeof start.json?.upload_id === "string" ? start.json.upload_id : "";
            if (uploadId === "") {
                throw new Error("画像の送信準備情報を受け取れませんでした。");
            }
            for (const image of prepared.images) {
                const sent = await this.sendImage(uploadId, image);
                if (!sent)
                    return;
            }
            const finalize = await this.postJson({ action: "finalize", upload_id: uploadId });
            if (finalize.status < 200 || finalize.status >= 300) {
                await this.cancelImageUpload(uploadId);
                this.showSendResult(finalize.status, this.responseMessage(finalize));
                return;
            }
            uploadId = "";
            new obsidian_1.Notice(`Tomosへ画像${prepared.images.length}点とMarkdownを送信しました。`);
        }
        catch (error) {
            if (uploadId !== "")
                await this.cancelImageUpload(uploadId);
            const message = error instanceof Error ? error.message : "Markdownを送信できませんでした。";
            new obsidian_1.Notice(`Tomos: ${message}`);
        }
    }
    async sendImage(uploadId, image) {
        const chunkCount = Math.ceil(image.data.byteLength / IMAGE_CHUNK_BYTES);
        for (let chunkIndex = 0; chunkIndex < chunkCount; chunkIndex += 1) {
            const start = chunkIndex * IMAGE_CHUNK_BYTES;
            const end = Math.min(start + IMAGE_CHUNK_BYTES, image.data.byteLength);
            const response = await (0, obsidian_1.requestUrl)({
                url: this.apiUrl(),
                method: "POST",
                headers: {
                    "Content-Type": "application/octet-stream",
                    "X-Tomos-Token": this.settings.token.trim(),
                    "X-Tomos-Action": "image",
                    "X-Tomos-Upload-Id": uploadId,
                    "X-Tomos-Image-Name": image.name,
                    "X-Tomos-Image-Type": image.mimeType,
                    "X-Tomos-Chunk-Index": String(chunkIndex),
                    "X-Tomos-Chunk-Count": String(chunkCount),
                    "X-Tomos-Total-Size": String(image.data.byteLength),
                },
                body: image.data.slice(start, end),
                throw: false,
            });
            if (response.status < 200 || response.status >= 300) {
                await this.cancelImageUpload(uploadId);
                this.showSendResult(response.status, this.responseMessage(response));
                return false;
            }
        }
        return true;
    }
    async preparePost(content, sourceFile) {
        const replacements = [];
        const images = new Map();
        const occupied = [];
        const wikiPattern = /!\[\[([^\]\n|]+)(?:\|([^\]\n]*))?\]\]/g;
        let wikiMatch;
        while ((wikiMatch = wikiPattern.exec(content)) !== null) {
            const target = wikiMatch[1].trim();
            const imageFile = this.resolveLocalImage(target, sourceFile);
            if (!imageFile)
                continue;
            const preparedImage = await this.prepareImage(imageFile);
            images.set(preparedImage.name, preparedImage);
            const alt = (wikiMatch[2] ?? imageFile.basename).trim() || imageFile.basename;
            replacements.push({
                start: wikiMatch.index,
                end: wikiMatch.index + wikiMatch[0].length,
                text: `![${this.escapeAlt(alt)}](images/${preparedImage.name})`,
            });
            occupied.push({ start: wikiMatch.index, end: wikiMatch.index + wikiMatch[0].length });
        }
        const markdownPattern = /!\[([^\]\n]*)\]\(([^)\n]+)\)/g;
        let markdownMatch;
        while ((markdownMatch = markdownPattern.exec(content)) !== null) {
            const start = markdownMatch.index;
            const end = start + markdownMatch[0].length;
            if (occupied.some((range) => start >= range.start && end <= range.end))
                continue;
            const rawTarget = markdownMatch[2].trim();
            if (/^(?:https?:|data:|#)/i.test(rawTarget))
                continue;
            if (/^images\/tms-[a-f0-9]{16}\.(?:jpg|jpeg|png|gif|webp)$/i.test(rawTarget))
                continue;
            const target = this.normalizedMarkdownTarget(rawTarget);
            if (target === "")
                continue;
            const imageFile = this.resolveLocalImage(target, sourceFile);
            if (!imageFile) {
                throw new Error(`画像「${target}」がVault内に見つかりません。`);
            }
            const preparedImage = await this.prepareImage(imageFile);
            images.set(preparedImage.name, preparedImage);
            replacements.push({
                start,
                end,
                text: `![${this.escapeAlt(markdownMatch[1])}](images/${preparedImage.name})`,
            });
        }
        if (images.size > MAX_IMAGE_COUNT) {
            throw new Error(`画像は${MAX_IMAGE_COUNT}点まで送信できます。`);
        }
        let rewritten = content;
        replacements.sort((left, right) => right.start - left.start);
        for (const replacement of replacements) {
            rewritten = rewritten.slice(0, replacement.start) + replacement.text + rewritten.slice(replacement.end);
        }
        return { content: rewritten, images: Array.from(images.values()) };
    }
    resolveLocalImage(target, sourceFile) {
        let linkPath = target.trim();
        if (linkPath.startsWith("<") && linkPath.endsWith(">")) {
            linkPath = linkPath.slice(1, -1).trim();
        }
        try {
            linkPath = decodeURIComponent(linkPath);
        }
        catch {
        }
        linkPath = linkPath.replace(/^\/+/, "");
        const file = this.app.metadataCache.getFirstLinkpathDest(linkPath, sourceFile.path);
        if (!(file instanceof obsidian_1.TFile))
            return null;
        return IMAGE_EXTENSIONS[file.extension.toLowerCase()] ? file : null;
    }
    normalizedMarkdownTarget(rawTarget) {
        const angleMatch = rawTarget.match(/^<([^>]+)>/);
        if (angleMatch)
            return angleMatch[1].trim();
        const titleMatch = rawTarget.match(/^(\S+)(?:\s+["'][^"']*["'])?$/);
        return titleMatch ? titleMatch[1].trim() : rawTarget;
    }
    async prepareImage(file) {
        const format = IMAGE_EXTENSIONS[file.extension.toLowerCase()];
        if (!format)
            throw new Error(`画像「${file.name}」の形式には対応していません。`);
        const data = await this.app.vault.readBinary(file);
        if (data.byteLength <= 0)
            throw new Error(`画像「${file.name}」が空です。`);
        if (data.byteLength > MAX_IMAGE_BYTES)
            throw new Error(`画像「${file.name}」は10MB以下にしてください。`);
        const digest = await crypto.subtle.digest("SHA-256", data);
        const hash = Array.from(new Uint8Array(digest))
            .map((value) => value.toString(16).padStart(2, "0"))
            .join("");
        return {
            name: `tms-${hash.slice(0, 16)}.${format.extension}`,
            data,
            mimeType: format.mimeType,
        };
    }
    escapeAlt(alt) {
        return alt.replace(/\\/g, "\\\\").replace(/\]/g, "\\]").replace(/\n/g, " ");
    }
    async postJson(payload) {
        return (0, obsidian_1.requestUrl)({
            url: this.apiUrl(),
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-Tomos-Token": this.settings.token.trim(),
            },
            body: JSON.stringify(payload),
            throw: false,
        });
    }
    async cancelImageUpload(uploadId) {
        if (uploadId === "")
            return;
        try {
            await this.postJson({ action: "cancel", upload_id: uploadId });
        }
        catch {
        }
    }
    responseMessage(response) {
        if (response.json && typeof response.json === "object" && "message" in response.json) {
            const message = response.json.message;
            if (typeof message === "string" && message.trim() !== "")
                return message;
        }
        return "";
    }
    showSendResult(status, serverMessage = "") {
        if (status >= 200 && status < 300) {
            new obsidian_1.Notice("Tomosへ送信しました。");
        }
        else if (serverMessage !== "") {
            new obsidian_1.Notice(`Tomos: ${serverMessage}`);
        }
        else if (status === 401) {
            new obsidian_1.Notice("Tomos: 認証に失敗しました。");
        }
        else if (status === 409) {
            new obsidian_1.Notice("Tomos: 同名ファイルが受信箱にあります。");
        }
        else if (status === 413) {
            new obsidian_1.Notice("Tomos: Markdownまたは画像のサイズが大きすぎます。");
        }
        else {
            new obsidian_1.Notice("Tomos: Markdownを送信できませんでした。");
        }
    }
    apiUrl() {
        return `${this.settings.tomosUrl.trim().replace(/\/+$/, "")}/post/inbox/api/`;
    }
    async loadSettings() {
        this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    }
    async saveSettings() {
        await this.saveData(this.settings);
    }
}
exports.default = TomosPublisherPlugin;
class TomosPublisherSettingTab extends obsidian_1.PluginSettingTab {
    constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
    }
    display() {
        const { containerEl } = this;
        containerEl.empty();
        containerEl.createEl("h2", { text: "Tomos Publisher" });
        new obsidian_1.Setting(containerEl)
            .setName("Tomos URL")
            .setDesc("例: https://tomoswords.org/dev/")
            .addText((text) => text
            .setPlaceholder("https://tomoswords.org/dev/")
            .setValue(this.plugin.settings.tomosUrl)
            .onChange(async (value) => {
            this.plugin.settings.tomosUrl = value.trim();
            await this.plugin.saveSettings();
        }));
        new obsidian_1.Setting(containerEl)
            .setName("投稿用トークン")
            .setDesc("Tomos Postのセキュリティ画面で発行した専用トークンです。")
            .addText((text) => {
            text.inputEl.type = "password";
            text.setValue(this.plugin.settings.token).onChange(async (value) => {
                this.plugin.settings.token = value.trim();
                await this.plugin.saveSettings();
            });
        });
        new obsidian_1.Setting(containerEl)
            .setName("Tomos記事の作成フォルダ")
            .setDesc("Vault内の既存フォルダを指定します。空欄または存在しない場合はVaultルートへ保存します。フォルダは自動作成しません。")
            .addText((text) => text
            .setPlaceholder("例: Tomos")
            .setValue(this.plugin.settings.articleFolder)
            .onChange(async (value) => {
            this.plugin.settings.articleFolder = value.trim();
            await this.plugin.saveSettings();
        }));
        new obsidian_1.Setting(containerEl)
            .setName("Tomos接続テスト")
            .addButton((button) => button.setButtonText("接続テスト").onClick(async () => {
            await this.plugin.testConnection();
        }));
        new obsidian_1.Setting(containerEl)
            .setName("Tomos用Markdown")
            .setDesc("Front MatterやTomosで使えるMarkdown記法を公式ガイドで確認できます。")
            .addButton((button) => button.setButtonText("書き方を見る").onClick(() => {
            this.plugin.openMarkdownGuide();
        }));
    }
}
